# Entire java Pipeline

name: Main-CI

on:
  workflow_dispatch:
    inputs:
      Artefacts_S3:
        description: 'Upload a artefacts into S3 only when initiate a CI manually'
        default: 'false'
        required: true
  push:
  pull_request:
    branch:
      - master

jobs:
  main_CI:
    name: Main CI  
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Maven deploy
        run: mvn clean install

      - name: File verification
        run: ls -lrt target/*

  upload_Artefacts:
      name: Upload Artefacts
      runs-on: ubuntu-latest
      needs: main_CI

      steps:
        - name: Upload file to local
          if: github.event.inputs.Artefacts_S3 == 'true'
          run: scp ${{ secrets.USER_ID }}@${{ secrets.MACHINE_ID }}:${{ secrets.MACHINE_PATH }}
