# Entire java Pipeline

name: Main-CI

on:
  workflow_dispatch:
    inputs:
      Artefacts_S3:
        description: 'Upload a artefacts into S3 only when initiate a CI manually'
        default: 'false'
        required: true
  push:
  pull_request:
    branch:
      - master

jobs:
  main_CI:
    name: Main CI  
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Maven deploy
        run: mvn clean install

      - name: File verification
        run: ls -lrt target/*

      - name: Upload Artefacts
        if: github.event.inputs.Artefacts_S3 == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: java_jar
          path: target/*.jar
          retention-days: 1

  upload_Artefacts:
      name: Upload Artefacts
      runs-on: ubuntu-latest
      needs: main_CI

      steps:

        - name: Check secrets
          run: |
            if [ -z "${{ secrets.MACHINE_IP }}" ]; then echo "MACHINE_ID is missing"; else echo "MACHINE_ID OK"; fi
            if [ -z "${{ secrets.USER_ID }}" ]; then echo "USER_ID is missing"; else echo "USER_ID OK"; fi
            if [ -z "${{ secrets.MACHINE_PATH }}" ]; then echo "MACHINE_PATH is missing"; else echo "MACHINE_PATH OK"; fi
            if [ -z "${{ secrets.SSH_KEY }}" ]; then echo "SSH_KEY is missing"; else echo "SSH_KEY OK"; fi
        
        - name: Test connection
          run: |
            ping -c 3 ${{ secrets.MACHINE_IP }}

        - name: SSH setup
          if: github.event.inputs.Artefacts_S3 == 'true'
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
            chmod 600  ~/.ssh/id_ed25519
            echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            ssh-keyscan -H ${{ secrets.MACHINE_IP }} >> ~/.ssh/known_hosts
            ls -lrt ~/.ssh/*
        
        - name: Download Artefacts
          if: github.event.inputs.Artefacts_S3 == 'true'
          uses: actions/download-artifact@v4
          with:
            name: java_jar
            path: target/

        - name: Upload File to Local
          if: github.event.inputs.Artefacts_S3 == 'true'
          run: scp -i  ~/.ssh/id_ed25519  target/*.jar ${{ secrets.USER_ID }}@${{ secrets.MACHINE_IP }}:${{ secrets.MACHINE_PATH }}
